name: "SPECK"
description: "Technical documentation tool"
inputs:
  config:
    description: "Pandoc defaults file"
    required: true
  target:
    description: "Target directory"
    required: true
  version:
    description: "Version identifier"
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.config }}
    - ${{ inputs.target }}
    - "--metadata"
    - "version=${{ inputs.version }}"
